image: node:18

stages:
  - prepare
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm install
    # Instalar componentes shadcn/ui en src/components/ui
    - mkdir -p src/components/ui
    - npx shadcn-ui@latest add card --ui-dir src/components/ui --no-interactive
  artifacts:
    paths:
      - src/components/ui/ # Incluir los componentes de shadcn/ui generados
    expire_in: 1 hour

build:
  stage: build
  script:
    - npm install
    # Asegurarse de que los componentes de shadcn/ui estén disponibles
    - if [ ! -d "src/components/ui/card" ]; then
      mkdir -p src/components/ui &&
      npx shadcn-ui@latest add card --ui-dir src/components/ui --no-interactive;
      fi
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
