name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          yarn --version

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          CI: false

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          target: ${{ secrets.SSH_TARGET_DIR }}
          strip_components: 1
